USE se2db;
CREATE TABLE `se2db`.`world` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Country` VARCHAR(45) NOT NULL,
  `Total Infected` INT NULL,
  `Total Deaths` INT NULL,
  `Total Recovers` INT NULL,
  `Day` DATE NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (1,'United States',852610,84191,48295,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (2,'Spain',213024,89250,22157,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (3,'Italy',187327,25085,54543,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (4,'France',159877,21340,40657,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (5,'Germany',151175,5354,103300,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (6,'United Kingdom',138078,18738,0,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (7,'Turkey',98674,2376,1477,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (8,'Iran',87026,5481,64843,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (9,'China',82798,4632,77207,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (10,'Russia',67773,555,4891,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (11,'Brazil',46701,2940,25318,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (12,'Belgium',42797,6490,9800,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (13,'Canada',40824,2028,13986,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (14,'Netherlands',35729,4177,0,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (15,'Switzerland',28496,1538,19900,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (16,'Portugal',22353,820,1201,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (17,'India',21797,686,4376,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (18,'Peru',19250,530,7027,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (20,'Ireland',16671,769,9233,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (21,'Austria',15002,11694,522,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (22,'Israel',14592,191,5334,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (23,'Saudi Arabia',13930,121,1925,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (24,'Japan',11950,299,1424,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (25,'Chile',11812,168,5804,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (26,'Singapore',11178,12,896,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (27,'Ecuador',10850,537,1262,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (28,'Pakistan',10811,228,2337,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (29,'South Korea',10702,240,8411,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (30,'Mexico',10544,970,2627,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (31,'Poland',10511,454,1740,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (32,'Romania',10096,541,2478,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (33,'United Arab Emirates',8756,56,1637,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (34,'Denmark',8073,394,5384,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (35,'Belarus',8022,60,938,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (36,'Indonesia',7775,647,960,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (37,'Qatar',7764,10,750,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (38,'Norway',7361,191,32,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (39,'Serbia',7276,139,1063,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (40,'Ukraine',7170,187,504,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (40,'Ukraine',7170,187,504,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (41,'Czechia',7138,210,2152,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (42,'Philippines',6981,462,772,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (43,'Australia',6661,75,5045,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (44,'Malaysia',5603,3542,95,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (45,'Dominican Republic',5543,265,581,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (46,'Panama',4992,144,255,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (47,'Colombia',4356,870,206,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (48,'Finland',4284,2000,172,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (49,'Bangladesh',4186,127,108,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (50,'Luxembourg',3665,83,711,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (51,'Morocco',3568,155,456,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (52,'Argentina',3435,165,919,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (53,'Thailand',2839,50,2430,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (54,'Greece',2463,125,577,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (55,'Kuwait',2399,14,498,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (56,'Kazakhstan',2289,20,560,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (57,'Hungary',2284,239,390,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (58,'Bahrain',2217,8,1082,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (59,'Croatia',1981,50,883,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (60,'Iceland',1789,10,1509,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (61,'Uzbekistan',1758,7,561,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (62,'Uzbekistan',1716,9,307,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (63,'Iraq',1677,83,1171,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (64,'Estonia',1592,45,192,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (65,'Azerbaijan',1548,20,948,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (66,'Armenia',1523,24,659,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (67,'New Zealand',1456,17,1095,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (68,'Bosnia Herzegovina',1413,54,485,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (69,'Lithuania',1398,40,399,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (70,'Slovenia',1366,211,79,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (71,'Cameroon',1334,43,668,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (72,'Slovakia',1325,15,288,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (73,'Macedonia',1300,56,301,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (74,'Afghanistan',1279,42,179,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (75,'Cuba',1235,365,43,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (76,'Ghana',1154,9,99,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (77,'Bulgaria',1097,52,190,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (78,'Hong Kong',1036,4,699,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (79,'Ivory Coast',1004,14,359,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (80,'Djibouti',986,2,252,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (81,'Nigeria',981,31,197,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (82,'Tunisia',981,38,190,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (83,'Guinea',862,6,170,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (84,'Cyprus',795,13,98,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (85,'Latvia',778,11,133,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (86,'Andorra',723,37,333,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (87,'Diamond Princess',712,13,645,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (88,'Bolivia',703,43,44,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (89,'Lebanon',688,22,140,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (90,'Costa Rica',686,6,196,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (91,'Niger',671,24,256,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (92,'Albania',663,27,385,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (93,'Kyrgyzstan',631,8,302,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (94,'Burkina Faso',616,41,410,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (95,'Uruguay',557,12,345,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (96,'Channel Islands',521,29,295,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (97,'Honduras',519,27,31,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (98,'San Marino',501,40,63,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (99,'Palestine',480,4,92,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (100,'Senegal',479,6,257,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (101,'San Marino',463,2,125,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (102,'Malta',447,3,223,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (103,'Jordan',437,7,318,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (104,'Georgia',431,5,114,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (105,'Taiwan',428,6,264,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (106,'Réunion',412,0,238,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (107,'Congo [DRC]',394,25,48,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (108,'Guatemala',384,11,30,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (109,'Sri Lanka',379,7,107,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (110,'Mayotte',354,4,144,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (111,'Kenya',336,14,89,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (112,'Mauritius',331,9,266,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (113,'Somalia',328,16,8,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (114,'Montenegro',319,10,123,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (115,'Venezuela',311,10,126,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (116,'Mali',309,21,77,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (117,'Isle of Man',307,16,221,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (118,'Tanzania',284,10,48,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (119,'Vietnam',270,0,224,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (120,'El Salvador',261,8,72,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (121,'Jamaica',257,6,28,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (122,'Paraguay',220,9,70,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (123,'Faeroe Islands',187,0,178,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (124,'Republic of the Congo',186,6,16,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (125,'Sudan',174,16,14,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (126,'Martinique',170,14,77,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (127,'Gabon',167,2,24,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (128,'Rwanda',154,0,87,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (129,'Guadeloupe',149,12,82,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (130,'Myanmar',139,5,9,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (131,'Brunei',138,1,120,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (132,'Gibraltar',133,0,129,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (133,'Cambodia',122,0,110,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (134,'Madagascar',122,0,61,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (135,'Liberia',117,8,25,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (136,'Ethiopia',117,3,25,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (137,'Maldives',116,0,16,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (138,'Trinidad and Tobago',115,8,48,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (139,'French Guiana',107,1,84,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (140,'Aruba',100,2,68,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (141,'Bermuda',99,5,39,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (142,'Monaco',94,4,35,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (143,'Togo',90,6,59,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (144,'Cape Verde',88,1,1,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (145,'Equatorial Guinea',84,1,7,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (146,'Sierra Leone',82,2,10,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (147,'Liechtenstein',81,1,55,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (148,'Barbados',76,6,30,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (149,'Zambia',76,3,37,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (150,'Uganda',74,0,46,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (151,'Sint Maarten',73,12,22,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (152,'Bahamas',72,11,14,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (153,'Haiti',72,5,2,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (154,'Guyana',70,7,12,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (155,'Cayman Islands',66,1,7,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (156,'Libya',60,2,18,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (157,'French Polynesia',57,0,36,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (158,'Benin',54,1,27,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (159,'Guinea-Bissau',50,0,3,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (160,'Nepal',48,0,10,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (161,'Mozambique',46,0,12,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (162,'Macao',45,0,27,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (163,'Syria',42,3,6,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (164,'Chad',40,0,8,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (165,'Eritrea',39,0,11,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (166,'Saint Martin',38,2,20,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (167,'Swaziland',36,1,10,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (168,'Mongolia',36,0,9,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (168,'Mongolia',36,0,9,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (168,'Mongolia',36,0,9,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (169,'Malawi',33,3,3,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (170,'Zimbabwe',29,4,2,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (171,'Angola',25,2,6,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (172,'Antigua and Barbuda',24,10,3,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (173,'Timor-Leste',23,0,1,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (174,'Botswana',22,0,1,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (175,'Laos',19,0,4,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (176,'Belize',18,2,5,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (177,'Fiji',18,0,10,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (178,'New Caledonia',18,0,17,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (179,'Central African Republic',16,0,10,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (180,'Dominica',16,0,9,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (181,'Namibia',16,0,7,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (182,'Grenada',15,0,7,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (183,'Saint Kitts and Nevis',15,0,2,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (184,'Saint Lucia',15,0,15,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (185,'Curaçao',14,1,11,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (186,'Saint Vincent and the Grenadines',14,0,5,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (187,'Falkland Islands',12,0,11,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (188,'Nicaragua',11,3,7,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (189,'Burundi',11,1,4,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (190,'Turks and Caicos',11,1,4,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (191,'Greenland',11,0,11,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (192,'Montserrat',11,0,2,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (193,'Seychelles',11,0,6,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (194,'Gambia',10,1,2,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (195,'Suriname',10,1,6,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (196,'MS Zaandam',9,0,2,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (197,'Vatican City',9,0,2,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (198,'Papua New Guinea',8,0,0,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (199,'Mauritania',7,1,6,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (200,'Bhutan',7,0,3,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (201,'St. Barth',6,0,6,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (202,'Western Sahara',6,0,5,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (203,'British Virgin Islands',5,1,3,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (204,'Caribbean Netherlands',5,0,0,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (205,'South Sudan',5,0,0,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (206,'Sao Tome and Principe',4,0,0,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (207,'Anguilla',3,0,1,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (208,'Saint Pierre Miquelon',1,0,0,NULL);
INSERT INTO `se2db`.`world` (`ID`,`Country`,`Total Infected`,`Total Deaths`,`Total Recovers`,`Day`) VALUES (209,'Yemen',1,0,1,NULL);
